# Generated by Django 4.2.1 on 2023-05-18 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adherent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250)),
                ('prenom', models.CharField(max_length=250)),
                ('telephone', models.CharField(max_length=250)),
                ('email', models.EmailField(default='', max_length=250)),
                ('caution', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Auteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250)),
                ('prenom', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Editeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emplacement', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Usure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Livre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=250)),
                ('description', models.TextField(default='', max_length=2048)),
                ('isbn', models.CharField(default='', max_length=250)),
                ('archive', models.BooleanField(default=False)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backoffice.auteur')),
                ('editeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backoffice.editeur')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backoffice.genre')),
            ],
        ),
        migrations.CreateModel(
            name='Exemplaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('livre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backoffice.livre')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backoffice.stock')),
                ('usure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backoffice.usure')),
            ],
        ),
        migrations.CreateModel(
            name='Emprunt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_emprunt', models.DateField(verbose_name='date emprunt')),
                ('date_retour', models.DateField(verbose_name='date retour')),
                ('status', models.CharField(max_length=250)),
                ('adherent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backoffice.adherent')),
                ('exemplaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backoffice.exemplaire')),
            ],
        ),
    ]
